### ISSUE TITLE
Laravel Recipe Improvements

### ISSUE THREAD

**Issue by barryvdh** [deployphp/deployer#619]
| Q | A |
| --- | --- |
| Issue Type | Feature Request |

I see a few issues have been opened for Laravel. To keep it central, imho it needs the following features:
- [x] Storage/writable folder improvements (#572 #622 + below)
- [x] Public storage folder symlink to shared storage (see quote below)
- [ ] Clear cache after deployments (eg. cached views/html parts; `php artisan cache:clear`
- [ ] Clear old cache and cache new config; both for speed and security (`php artisan config:cache`) (#527)
- [x] Update shared folders _before_ vendors. This because of `php artisan optimize` being dependant on environment, so needs shared `.env` file.
- [ ] Add optional helpers tasks for `php artisan migrate` and `php artisan db:seed`, using the `--force` flag for non-interactive mode (but should perhaps confirm on the deployer side. And perhaps `php artisan migrate:status` for info. (#541 #622)

About Laravel folders, should we update the recipe to follow the 'guidelines' set by Taylor Otwell http://taylorotwell.com/spark-storage/

> When using deployment systems like Envoyer, an entirely fresh copy of the repository is installed with each deploy and the storage directory is attached to a permanent storage directory using a symbolic link. If you store your user uploads in public, they will all go missing on your subsequent deployment. **The solution is to store the uploads in your persistent storage directory and then create a symbolic link from your public directory to your storage directory during your deployment process.**
> 
> Before yesterday, there was no conventional place to store these user uploads other than “anywhere you want within the storage directory”. After reviewing a few libraries in other languages, it became apparent that there would be great benefit to designating a standard location within the storage directory for files intended to be publicly accessible. So, I created the storage/app/public directory in the Laravel repository so that it will be present on all future installs of Laravel 5.2.

So the default would be this
- Shared: `.env` + entire `storage` folder
- Writable:  `storage` + `bootstrap/cache` (I would recommend sharing the entire storage folder)
- Create symlink `public/storage` to `storage/app/public` (`run("ln -s {{deploy_path}}/storage/app/public {{deploy_path}}/public/storage ");` ?)

**Comment by oanhnn** [comment]
@barryvdh Can you send link about 

> Create symlink public/storage to storage/app/public (run("ln -s {{deploy_path}}/storage/app/public {{deploy_path}}/public/storage "); ?)

in Laravel document. I read http://taylorotwell.com/spark-storage/ but i support it only it is included Laravel document.

**Comment by barryvdh** [comment]
Okay, I've added a PR here: https://github.com/laravel/docs/pull/2265

**Comment by barryvdh** [comment]
See https://laravel.com/docs/5.2/filesystem#configuration

> The public disk is meant for files that are going to be publicly accessible. By default, the public disk uses the local driver and stores these files in storage/app/public. To make them accessible from the web, you should create a symbolic link from public/storage to storage/app/public. This convention will keep your publicly accessible files in one directory that can be easily shared across deployments when using zero down-time deployment systems like Envoyer.

**Comment by oanhnn** [comment]
- [x] Storage/writable folder improvements (resolved in #622 )
- [x] Public storage folder symlink to shared storage.(resolved in #625 )
- [x] Clear cache after deployments (eg. cached views/html parts; `php artisan cache:clear` (resolved in #625 )
- [x] Clear old cache and cache new config; both for speed and security (`php artisan config:cache`) (resolved in #625 )
- [x] Update shared folders *before* vendors. This because of `php artisan optimize` being dependant on environment, so needs shared `.env` file. (resolved in #622 )
- [x] Add optional helpers tasks for `php artisan migrate` and `php artisan db:seed`, using the `--force` flag for non-interactive mode (but should perhaps confirm on the deployer side. And perhaps `php artisan migrate:status` for info. (resolved in #625 )

**Comment by Rexeh** [comment]
Hey Barry,

I think this line is wrong?

Create symlink public/storage to storage/app/public (run("ln -s {{deploy_path}}/storage/app/public {{deploy_path}}/public/storage "); ?)

It should be the following?

Create symlink public/storage to storage/app/public (run("ln -s {{deploy_path}}/storage/app/public {{**release_path**}}/public/storage "); ?)

**Comment by barryvdh** [comment]
Hmm no shouldn't matter, as storage is a symlink anyways.

**Comment by Rexeh** [comment]
The following line is what I had to use:

  run("ln -s {{deploy_path}}/shared/storage/app/public {{deploy_path}}/current/public/storage");

**Comment by barryvdh** [comment]
Oh probably mixed release path and deploy path indeed. But was just an example, haven't actually used this in production yet.

**Comment by barryvdh** [comment]
And most is already implemented here: https://github.com/deployphp/deployer/pull/625

**Comment by elfet** [comment]
Merged.
